# 参考
# https://qiita.com/Broccolingual/items/bf0fa0d00920fbfda371
# https://zenn.dev/snowcait/articles/18c9137f49e378

name: Action # GitHub Actionsにつける名前。任意で良い。

on:
  schedule:
    - cron: '0 0 * * *' # cronで定期実行(毎朝9時)

jobs:
  build:
    runs-on: ubuntu-latest # 最新のubuntu環境で下記のジョブを実行
    steps:
      - uses: actions/checkout@v2 # おまじない

      - name: Setup python # ワークフローのセクションごとに設定する名前。特に設定する必要はないが、どこでエラーが起きているかを把握する為にも設定しておいた方が良い。
        uses: actions/setup-python@v2 # Pythonのセットアップ
        with:
          python-version: "3.9.0" # Pythonのバージョン指定

      - name: Install dependencies # Pythonの依存環境のインストール
        run: | #このような書き方で複数行を一気に実行することができる。
          pip install -r requirements.txt

      - name: Run scrap.py # Pythonファイルの実行
        run: |
          python scrap.py

      - name: Commit and Push # 変更があれば、実行した結果をプッシュして変更をレポジトリに反映
        run: |
          git add -N .
          if ! git diff --exit-code --quiet
          then
            git config --global user.name "Yuriko Takahashi"
            git config --global user.email yuricocoa3618@gmail.com
            git add -A
            git commit -m "add new file"
            git pull
            git push origin master
          fi
